import '@/lib/wdyr'; // Must be first import for why-did-you-render

import type { Metadata } from "next";
import "./globals.css";
import { Message } from "@/components/ui/sonner";
import { MeStoreInit } from "@/components/app/me-store-init";
import { RouteSync } from "@/components/app/route-sync";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-dvh bg-background font-sans text-foreground antialiased`}>
        <MeStoreInit />
        <RouteSync />
        {children}
        <Message position='top-center' />
      </body>
    </html>
  );
}
