import '@/lib/wdyr'; // Must be first import for why-did-you-render

import type { Metadata } from "next";
import { cookies, headers } from 'next/headers';
import "./globals.css";
import { Message } from "@/components/ui/sonner";
import { MeStoreInit } from "@/components/app/me-store-init";
import { RouteSync } from "@/components/app/route-sync";
import { ThemeProvider } from "@/components/app/theme-provider";
import { I18nProvider } from '@/lib/i18n/provider';
import {
  DEFAULT_LOCALE,
  LOCALE_COOKIE_KEY,
  normalizeLocale,
  resolveLocale,
} from '@/lib/i18n/locale';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const headerStore = await headers();
  const initialLocale =
    normalizeLocale(cookieStore.get(LOCALE_COOKIE_KEY)?.value) ??
    resolveLocale({
      acceptLanguage: headerStore.get('accept-language'),
    }) ??
    DEFAULT_LOCALE;

  return (
    <html lang={initialLocale} suppressHydrationWarning>
      <body className={`min-h-dvh bg-background font-sans text-foreground antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
          storageKey="contexta-theme"
        >
          <I18nProvider initialLocale={initialLocale}>
            <MeStoreInit />
            <RouteSync />
            {children}
            <Message position='top-center' />
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
