export const SHARE_REPOSITORY = Symbol('SHARE_REPOSITORY');
export const SHARE_SNAPSHOT_REPOSITORY = Symbol('SHARE_SNAPSHOT_REPOSITORY');
export const SHARE_ACCESS_LOG_REPOSITORY = Symbol('SHARE_ACCESS_LOG_REPOSITORY');
