export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  FORMAT_NOT_SUPPORTED: 'FORMAT_NOT_SUPPORTED',
  FILE_CONTENT_EMPTY: 'FILE_CONTENT_EMPTY',
  INVALID_PDF: 'INVALID_PDF',
  INVALID_DOCX: 'INVALID_DOCX',
  STREAM_ERROR: 'STREAM_ERROR',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  DAILY_COPY_NOT_FOUND: 'DAILY_COPY_NOT_FOUND',
  ATTACHMENT_INDEXING_NOT_CONFIGURED: 'ATTACHMENT_INDEXING_NOT_CONFIGURED',
  ATTACHMENT_SEARCH_NOT_CONFIGURED: 'ATTACHMENT_SEARCH_NOT_CONFIGURED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
