export const AI_CONVERSATION_REPOSITORY = Symbol('AI_CONVERSATION_REPOSITORY');
export const AI_MESSAGE_REPOSITORY = Symbol('AI_MESSAGE_REPOSITORY');
export const AI_CHAT_PROVIDER = Symbol('AI_CHAT_PROVIDER');
